/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projekoop;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import projekoop.scenes.StartScene;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;


public class App extends Application{
   
    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception{

        Button buttonStart = new Button("MULAI");
        buttonStart.setMaxSize(100, 200);
        buttonStart.setAlignment(Pos.CENTER);
        buttonStart.setOnAction(V -> {
            StartScene startScene = new StartScene(stage);
            startScene.show();
        });
        
        Label tittle = new Label("N3 GALLERY");
        
        VBox vbox = new VBox();
        tittle.setFont(Font.font("Arial",20));
        vbox.getChildren().add(tittle);
        vbox.getChildren().add(buttonStart);
        vbox.setSpacing(12.0);
        vbox.setAlignment(Pos.CENTER);
                
        
        Scene scene = new Scene(vbox, 320,512);
        stage.setScene(scene);
        stage.setTitle("N3 Gallery");
        stage.show();
    }

    

}
